# Generated by Django 5.2.3 on 2025-07-07 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_package_foods_package_hotels'),
        ('destination', '0001_initial'),
        ('food', '0001_initial'),
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_package', to='core.address')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_packages', to='destination.destination')),
                ('foods', models.ManyToManyField(blank=True, related_name='booking_packages', to='food.food')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_packages', to='hotel.hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
