# Generated by Django 5.2.3 on 2025-07-07 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_end_date_alter_booking_start_date'),
        ('core', '0004_package_end_date_package_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_package', to='core.address'),
        ),
    ]
