# Generated by Django 5.2.3 on 2025-07-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package'),
        ('food', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='packages', to='food.food'),
        ),
        migrations.AddField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='packages', to='hotel.hotel'),
        ),
    ]
