# Generated by Django 5.2.3 on 2025-07-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_package_foods_package_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
